### ISSUE TITLE
sqs plugin issue

### ISSUE THREAD

**Issue by kostaatsk** [bpaquet/node-logstash#140]
Hello,

I am getting the following error when I try to use sqs. Zeromq and file plugins seem to be working.

```[Wed, 30 Nov 2016 21:45:28 GMT] NOTICE Starting node-logstasth-agent 0.0.5
[Wed, 30 Nov 2016 21:45:28 GMT] INFO Max http socket 100
[Wed, 30 Nov 2016 21:45:28 GMT] INFO Alarm file /var/db/node-logstash/on_alarm
[Wed, 30 Nov 2016 21:45:28 GMT] INFO Loading config files from : /etc/node-logstash/plugins.conf.d
[Wed, 30 Nov 2016 21:45:28 GMT] INFO Files loaded from directory, 3 urls found
[Wed, 30 Nov 2016 21:45:28 GMT] INFO Loading config : 6 urls
[Wed, 30 Nov 2016 21:45:28 GMT] ERROR Unable to load urls from command line
[Wed, 30 Nov 2016 21:45:28 GMT] ERROR Error: Cannot find module '/opt/node-logstash/node_modules/aws-sdk/apis/metadata.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at buildServiceMap (/opt/node-logstash/node_modules/aws-sdk/lib/api_loader.js:13:16)
    at Object.getServices [as services] (/opt/node-logstash/node_modules/aws-sdk/lib/api_loader.js:42:3)
    at Object.<anonymous> (/opt/node-logstash/node_modules/aws-sdk/lib/services.js:7:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by kostaatsk** [comment]
Ok it seems to be an issue with an outdated version of aws-sdk, it is set to 2.2.x and it works fine with 2.7.9, can you please modify  the dependency in packages.json to
"aws-sdk": "2.7.x"
